sudo: false
language: node_js
node_js:
- '10'
- '12'
- '14'
cache:
  directories:
  - node_modules
before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
script:
- npm run build
jobs:
  include:
  - stage: npm release
    node_js: '12'
    script: npm run build
    deploy:
      provider: npm
      skip_cleanup: true
      on:
        branch: release/*
      email: developer@uiza.io
      api_key:
        secure: GzQC6e6yjZLsSwNq7J/Z9Pr6Kq8gsoSylUT7G9u8Lh1I1QF3Cx5Mjj9/5CM/uYn97Qu1m+G4PcYJZEklh3MF2XMhUS9Ok0BmwleHkWksXkdX/x1e2WpZZwkf/RuhhqcTMcavQBNSD10s5/MG9LflE6SBsmg8O/IQmsSWrHbUGSKOluXaJBeMhzSyUQFUoeSnKSIj/JvYM5ywRD6locxDLQ8GwXfX/rdv8VcXLquOecuDsd6C42WLWApcX0+rCStwiOO0Gd4aIF1f65I7MAq8C0yaeohP21qaa/RVJGjy5FyM3t5yE/c1ulrZDo2DRzleNZS9B/MORbwYhrutYrdQc6dZDTCKjnRWLPW8fzbSNZB5CsitpWWlExI8XoSQ6EZmbUjpAW8u7CoF7vRFYXv3lfdK9tl8RcST7iUm4gTtmiytniIhQvpVp6WYfEQG92uU5oFJ8klewYc3StVAIpdnSaXQknL+/KFog5tCXVTK//atSEI7khXMYJkcnDchCGZGAnmuVllUNAOmLkWIsS+4E1Wzhgkn5ty8bTMeWp7ws8e5hLJojxPU0NJ1s3vpYlDuFc2evkj30z6pnPPqD3KDRVIaNPbU4tDHQFK1njmMmHXK/74Yp19Dd+Rl6+SK3U4ufh9+UbhS9U9dKyOCmEIP6ye1rVOUvidx3yxvynOCZiY=
notifications:
  slack:
    rooms:
      secure: Bgz8NlAPizegtSD8++V6w8cMXXWDVGHFszxg+gJJRwT+3smvJUP+PQONVozMgoPXWXGrk9HbTALqJ2MYtxB4TJWbeiOugcNDUmIg/GAJGEgGAc5Tbu2XuBO7U28b9zueKpZTAA0FfT2kXGQLF1ohB7ovTtlykE7IT3a6t3IfNXCTug3zE7EgVLpi53XL30IAQotn7rHVhTMk1KOHFuP03gxGL3hpCruvkRPbZyNBh2188gqZBjrXkDD2sOTx+YERdNe8IyeTUOAp52omKpUHAvK5q90pprkWG6V0iu2iY/dCTgvLjc3DnH+0/8tT21yllHsxAxW8Mdk1j8ovaeQQxsa9gbiYZbT3MWB9cLzTTi2Q/k921V2Bhow/NCd/nYwfIyk7j0hEbRrA6bz7YXeXlnF+W3NjAASr/UV1T4vpcXsZkjLVylYC7UlpS/4fdAbUEEeZ90+lNTtL6Kh17WbEzc/HKPT4EsyPwTLnnQ94HXZiziVNjsZirWtpSs2AxHq9ryuqvX6NvrW6dAxOJ6LInub0CbtNHK+Wn88YZICJSMOz/NZWHjoPXNAXd/GIJ1kXUCSjejL5DOl2Vej4A5GU/JpoWZDfTgR+wdujiiduTTxqw1I/rphQTnVXZqdDjXCTxX872Lvf9tkITfJbtmxfKQAUsR0u5mOc34f1DKl8PRs=